### ISSUE TITLE
Update plugin on jenkins

### ISSUE THREAD

**Issue by GriffinHeart** [nanapi/jenkins-chatwork-plugin#5]
This is an awesome plugin, is it possible to update the version on Jenkins website?

**Comment by sue445** [comment]
@GriffinHeart  I have been delegated the release authority from @vexus2 , and I became a new maintainer.

I register to official update center as `v0.6.1`

This repository is moved to https://github.com/jenkinsci/chatwork-plugin

**Comment by GriffinHeart** [comment]
@sue445 Thank you :+1:
